const API_URL = `https://api.themoviedb.org/3`;
const API_KEY = `eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMDgwNzYwYjIzMTI4OWI5NmU0ODE1YzYwNDQ1MzM5ZCIsInN1YiI6IjY0YWMwYzYzZTI0YjkzMDBlMzI3YThhNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.LgN-PRKOtSLevLnOVfPIZ949JuxtZF7KWHhbTGJNx_E`;

export { API_URL, API_KEY };